/* AUTO-GENERATED by tools/build_videos.py — do not edit by hand. */
const VIDEOS = [
 {
  "key": "reels",
  "title": "Reels",
  "items": [
   {
    "f": "reels01",
    "t": "Falak Tak",
    "d": "January 31st 2025",
    "s": 0
   },
   {
    "f": "reels02",
    "t": "Jahan Main Jati Hu",
    "d": "January 31st 2025",
    "s": 0
   },
   {
    "f": "reels03",
    "t": "Kabhi Kabhi Kuch Toh Kaho",
    "d": "January 31st 2025",
    "s": 0
   },
   {
    "f": "reels04",
    "t": "Maine Koi Jaadu Nahi Kiya",
    "d": "January 10th 2025",
    "s": 0
   },
   {
    "f": "reels05",
    "t": "Tu Ishq Hain",
    "d": "February 2nd 2025",
    "s": 0
   },
   {
    "f": "reels06",
    "t": "Gali Gali Mere Naam Ke Deewane",
    "d": "March 14th 2025",
    "s": 0
   },
   {
    "f": "reels07",
    "t": "Tere Bina",
    "d": "February 13",
    "s": 0
   },
   {
    "f": "reels08",
    "t": "Zindagi Rubic Cube Jaisi",
    "d": "December 27th 2024",
    "s": 0
   },
   {
    "f": "reels09",
    "t": "With Bindi, Haayeee",
    "d": "January 31st 2025",
    "s": 0
   },
   {
    "f": "reels10",
    "t": "Kesa Ladka Chahiye",
    "d": "May 4th 2024",
    "s": 0
   }
  ]
 },
 {
  "key": "days",
  "title": "Days",
  "items": [
   {
    "f": "days01",
    "t": "College Holi Dance Party",
    "d": "March 11th 2025",
    "s": 0
   },
   {
    "f": "days02",
    "t": "Holi, Latepost",
    "d": "March 22nd 2025",
    "s": 0
   },
   {
    "f": "days03",
    "t": "The Whole World Is A Garden",
    "d": "March 7th 2025",
    "s": 0
   },
   {
    "f": "days04",
    "t": "First Resin Art",
    "d": "March 4th 2025",
    "s": 0
   },
   {
    "f": "days05",
    "t": "Sunset On The Way Home",
    "d": "January 19th 2025",
    "s": 0
   },
   {
    "f": "days06",
    "t": "First Meet Of 2025",
    "d": "January 16th 2025",
    "s": 0
   },
   {
    "f": "days07",
    "t": "Bhandara Day",
    "d": "",
    "s": 0
   },
   {
    "f": "days08",
    "t": "My Heartbeat",
    "d": "June 3rd 2025",
    "s": 0
   }
  ]
 },
 {
  "key": "bestie",
  "title": "Bestie",
  "items": [
   {
    "f": "bestie01",
    "t": "us being us",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie02",
    "t": "no context needed",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie03",
    "t": "peak chaos",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie04",
    "t": "my favourite people",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie05",
    "t": "partners in crime",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie06",
    "t": "this one still makes me laugh",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie07",
    "t": "unserious behaviour",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie08",
    "t": "the group chat, live",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie09",
    "t": "certified nonsense",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie10",
    "t": "happiest kind of loud",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie11",
    "t": "you two, always",
    "d": "",
    "s": 0
   },
   {
    "f": "bestie12",
    "t": "a whole mood",
    "d": "",
    "s": 0
   }
  ]
 }
];
